version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5050
      - DB_USER=postgres
      - DB_PASSWORD=Qq1234567
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    depends_on:
      - db
    volumes:
      - .env:/root/.env
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qq1234567
      POSTGRES_DB: subscriptions
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: